version: "3.7"

services:
    web:
        image: itec_app:latest
        volumes:
            - .:/app
        ports:
            - 9090:8000
        command: bash -c 'php artisan serve --host=0.0.0.0'
        depends_on:
            - db
        links:
            - db

    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USERNAME: cynax
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: itec
        ports:
            - 8203:3306
